apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: b05nve8zo-go 
  janus-idp.io/tekton: b05nve8zo-go
  backstage.io/kubernetes-id: b05nve8zo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b05nve8zo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  