apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: b05nve8zo-go-gitops
  description: This is GitOps manifest for b05nve8zo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: b05nve8zo-go
    backstage.io/kubernetes-id: b05nve8zo-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: b05nve8zo-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:b05nve8zo-go
